// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module axi_qspi_regs (
        input wire clk,
        input wire rst,

        output logic s_axil_awready,
        input wire s_axil_awvalid,
        input wire [6:0] s_axil_awaddr,
        input wire [2:0] s_axil_awprot,
        output logic s_axil_wready,
        input wire s_axil_wvalid,
        input wire [31:0] s_axil_wdata,
        input wire [3:0]s_axil_wstrb,
        input wire s_axil_bready,
        output logic s_axil_bvalid,
        output logic [1:0] s_axil_bresp,
        output logic s_axil_arready,
        input wire s_axil_arvalid,
        input wire [6:0] s_axil_araddr,
        input wire [2:0] s_axil_arprot,
        input wire s_axil_rready,
        output logic s_axil_rvalid,
        output logic [31:0] s_axil_rdata,
        output logic [1:0] s_axil_rresp,

        input axi_qspi_regs_pkg::axi_qspi_regs__in_t hwif_in,
        output axi_qspi_regs_pkg::axi_qspi_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [6:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Max Outstanding Transactions: 2
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [6:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [6:0] axil_awaddr;
    logic axil_wvalid;
    logic [31:0] axil_wdata;
    logic [3:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk or negedge hwif_in.rst_n) begin
        if(~hwif_in.rst_n) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil_arvalid && s_axil_arready) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil_araddr;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil_awvalid && s_axil_awready) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil_awaddr;
            end
            if(s_axil_wvalid && s_axil_wready) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil_wdata;
                axil_wstrb <= s_axil_wstrb;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil_arready = (!axil_arvalid || axil_ar_accept);
        s_axil_awready = (!axil_awvalid || axil_aw_accept);
        s_axil_wready = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<4; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd2) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[6:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = {axil_awaddr[6:2], 2'b0};
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[6:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    struct {
        logic is_wr;
        logic err;
        logic [31:0] rdata;
    } axil_resp_buffer[2];

    logic [1:0] axil_resp_wptr;
    logic [1:0] axil_resp_rptr;

    always_ff @(posedge clk or negedge hwif_in.rst_n) begin
        if(~hwif_in.rst_n) begin
            for(int i=0; i<2; i++) begin
                axil_resp_buffer[i].is_wr <= '0;
                axil_resp_buffer[i].err <= '0;
                axil_resp_buffer[i].rdata <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
        end else begin
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer[axil_resp_wptr[0:0]].is_wr <= '0;
                    axil_resp_buffer[axil_resp_wptr[0:0]].err <= cpuif_rd_err;
                    axil_resp_buffer[axil_resp_wptr[0:0]].rdata <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer[axil_resp_wptr[0:0]].is_wr <= '1;
                    axil_resp_buffer[axil_resp_wptr[0:0]].err <= cpuif_wr_err;
                end
                axil_resp_wptr <= axil_resp_wptr + 1'b1;
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                axil_resp_rptr <= axil_resp_rptr + 1'b1;
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil_bvalid = '0;
        s_axil_rvalid = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer[axil_resp_rptr[0:0]].is_wr) begin
                s_axil_bvalid = '1;
                if(s_axil_bready) axil_resp_acked = '1;
            end else begin
                s_axil_rvalid = '1;
                if(s_axil_rready) axil_resp_acked = '1;
            end
        end

        s_axil_rdata = axil_resp_buffer[axil_resp_rptr[0:0]].rdata;
        if(axil_resp_buffer[axil_resp_rptr[0:0]].err) begin
            s_axil_bresp = 2'b10;
            s_axil_rresp = 2'b10;
        end else begin
            s_axil_bresp = 2'b00;
            s_axil_rresp = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic STATUS;
        logic CLKDIV;
        logic SPICMD;
        logic SPIADR;
        logic SPILEN;
        logic SPIDUM;
        logic TXFIFO;
        logic RXFIFO;
        logic CS_DEF;
        logic CS_A_0;
        logic CS_M_0;
        logic CS_A_1;
        logic CS_M_1;
        logic CS_A_2;
        logic CS_M_2;
        logic CS_A_3;
        logic CS_M_3;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        is_valid_addr = '1; // No error checking on valid address access
        is_invalid_rw = '0;
        decoded_reg_strb.STATUS = cpuif_req_masked & (cpuif_addr == 7'h0);
        decoded_reg_strb.CLKDIV = cpuif_req_masked & (cpuif_addr == 7'h4);
        decoded_reg_strb.SPICMD = cpuif_req_masked & (cpuif_addr == 7'h8);
        decoded_reg_strb.SPIADR = cpuif_req_masked & (cpuif_addr == 7'hc);
        decoded_reg_strb.SPILEN = cpuif_req_masked & (cpuif_addr == 7'h10);
        decoded_reg_strb.SPIDUM = cpuif_req_masked & (cpuif_addr == 7'h14);
        decoded_reg_strb.TXFIFO = cpuif_req_masked & (cpuif_addr == 7'h18) & cpuif_req_is_wr;
        decoded_reg_strb.RXFIFO = cpuif_req_masked & (cpuif_addr == 7'h20) & !cpuif_req_is_wr;
        decoded_reg_strb.CS_DEF = cpuif_req_masked & (cpuif_addr == 7'h24);
        decoded_reg_strb.CS_A_0 = cpuif_req_masked & (cpuif_addr == 7'h28);
        decoded_reg_strb.CS_M_0 = cpuif_req_masked & (cpuif_addr == 7'h2c);
        decoded_reg_strb.CS_A_1 = cpuif_req_masked & (cpuif_addr == 7'h30);
        decoded_reg_strb.CS_M_1 = cpuif_req_masked & (cpuif_addr == 7'h34);
        decoded_reg_strb.CS_A_2 = cpuif_req_masked & (cpuif_addr == 7'h38);
        decoded_reg_strb.CS_M_2 = cpuif_req_masked & (cpuif_addr == 7'h3c);
        decoded_reg_strb.CS_A_3 = cpuif_req_masked & (cpuif_addr == 7'h40);
        decoded_reg_strb.CS_M_3 = cpuif_req_masked & (cpuif_addr == 7'h44);
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } sw_rst;
            struct {
                logic next;
                logic load_next;
            } trig_rx;
            struct {
                logic next;
                logic load_next;
            } trig_tx;
        } STATUS;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } div;
            struct {
                logic next;
                logic load_next;
            } bypass;
            struct {
                logic next;
                logic load_next;
            } cpol;
        } CLKDIV;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } cmd;
        } SPICMD;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } addr;
        } SPIADR;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } len;
        } SPILEN;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } dum;
        } SPIDUM;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } TXFIFO;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } cs;
        } CS_DEF;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } val;
        } CS_A_0;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } val;
        } CS_M_0;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } val;
        } CS_A_1;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } val;
        } CS_M_1;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } val;
        } CS_A_2;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } val;
        } CS_M_2;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } val;
        } CS_A_3;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } val;
        } CS_M_3;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } sw_rst;
            struct {
                logic value;
            } trig_rx;
            struct {
                logic value;
            } trig_tx;
        } STATUS;
        struct {
            struct {
                logic [7:0] value;
            } div;
            struct {
                logic value;
            } bypass;
            struct {
                logic value;
            } cpol;
        } CLKDIV;
        struct {
            struct {
                logic [31:0] value;
            } cmd;
        } SPICMD;
        struct {
            struct {
                logic [31:0] value;
            } addr;
        } SPIADR;
        struct {
            struct {
                logic [31:0] value;
            } len;
        } SPILEN;
        struct {
            struct {
                logic [31:0] value;
            } dum;
        } SPIDUM;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } TXFIFO;
        struct {
            struct {
                logic [31:0] value;
            } cs;
        } CS_DEF;
        struct {
            struct {
                logic [31:0] value;
            } val;
        } CS_A_0;
        struct {
            struct {
                logic [31:0] value;
            } val;
        } CS_M_0;
        struct {
            struct {
                logic [31:0] value;
            } val;
        } CS_A_1;
        struct {
            struct {
                logic [31:0] value;
            } val;
        } CS_M_1;
        struct {
            struct {
                logic [31:0] value;
            } val;
        } CS_A_2;
        struct {
            struct {
                logic [31:0] value;
            } val;
        } CS_M_2;
        struct {
            struct {
                logic [31:0] value;
            } val;
        } CS_A_3;
        struct {
            struct {
                logic [31:0] value;
            } val;
        } CS_M_3;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: axi_qspi_regs.STATUS.sw_rst
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.sw_rst.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.STATUS.sw_rst.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.STATUS.sw_rst.next = next_c;
        field_combo.STATUS.sw_rst.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge hwif_in.rst_n) begin
        if(~hwif_in.rst_n) begin
            field_storage.STATUS.sw_rst.value <= 1'h0;
        end else begin
            if(field_combo.STATUS.sw_rst.load_next) begin
                field_storage.STATUS.sw_rst.value <= field_combo.STATUS.sw_rst.next;
            end
        end
    end
    assign hwif_out.STATUS.sw_rst.value = field_storage.STATUS.sw_rst.value;
    // Field: axi_qspi_regs.STATUS.trig_rx
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.trig_rx.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.STATUS.trig_rx.value & ~decoded_wr_biten[8:8]) | (decoded_wr_data[8:8] & decoded_wr_biten[8:8]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.STATUS.trig_rx.next = next_c;
        field_combo.STATUS.trig_rx.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge hwif_in.rst_n) begin
        if(~hwif_in.rst_n) begin
            field_storage.STATUS.trig_rx.value <= 1'h0;
        end else begin
            if(field_combo.STATUS.trig_rx.load_next) begin
                field_storage.STATUS.trig_rx.value <= field_combo.STATUS.trig_rx.next;
            end
        end
    end
    assign hwif_out.STATUS.trig_rx.value = field_storage.STATUS.trig_rx.value;
    // Field: axi_qspi_regs.STATUS.trig_tx
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.trig_tx.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.STATUS.trig_tx.value & ~decoded_wr_biten[9:9]) | (decoded_wr_data[9:9] & decoded_wr_biten[9:9]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.STATUS.trig_tx.next = next_c;
        field_combo.STATUS.trig_tx.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge hwif_in.rst_n) begin
        if(~hwif_in.rst_n) begin
            field_storage.STATUS.trig_tx.value <= 1'h0;
        end else begin
            if(field_combo.STATUS.trig_tx.load_next) begin
                field_storage.STATUS.trig_tx.value <= field_combo.STATUS.trig_tx.next;
            end
        end
    end
    assign hwif_out.STATUS.trig_tx.value = field_storage.STATUS.trig_tx.value;
    // Field: axi_qspi_regs.CLKDIV.div
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CLKDIV.div.value;
        load_next_c = '0;
        if(decoded_reg_strb.CLKDIV && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CLKDIV.div.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.CLKDIV.div.next = next_c;
        field_combo.CLKDIV.div.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge hwif_in.rst_n) begin
        if(~hwif_in.rst_n) begin
            field_storage.CLKDIV.div.value <= 8'h2;
        end else begin
            if(field_combo.CLKDIV.div.load_next) begin
                field_storage.CLKDIV.div.value <= field_combo.CLKDIV.div.next;
            end
        end
    end
    assign hwif_out.CLKDIV.div.value = field_storage.CLKDIV.div.value;
    // Field: axi_qspi_regs.CLKDIV.bypass
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CLKDIV.bypass.value;
        load_next_c = '0;
        if(decoded_reg_strb.CLKDIV && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CLKDIV.bypass.value & ~decoded_wr_biten[8:8]) | (decoded_wr_data[8:8] & decoded_wr_biten[8:8]);
            load_next_c = '1;
        end
        field_combo.CLKDIV.bypass.next = next_c;
        field_combo.CLKDIV.bypass.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge hwif_in.rst_n) begin
        if(~hwif_in.rst_n) begin
            field_storage.CLKDIV.bypass.value <= 1'h0;
        end else begin
            if(field_combo.CLKDIV.bypass.load_next) begin
                field_storage.CLKDIV.bypass.value <= field_combo.CLKDIV.bypass.next;
            end
        end
    end
    assign hwif_out.CLKDIV.bypass.value = field_storage.CLKDIV.bypass.value;
    // Field: axi_qspi_regs.CLKDIV.cpol
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CLKDIV.cpol.value;
        load_next_c = '0;
        if(decoded_reg_strb.CLKDIV && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CLKDIV.cpol.value & ~decoded_wr_biten[31:31]) | (decoded_wr_data[31:31] & decoded_wr_biten[31:31]);
            load_next_c = '1;
        end
        field_combo.CLKDIV.cpol.next = next_c;
        field_combo.CLKDIV.cpol.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge hwif_in.rst_n) begin
        if(~hwif_in.rst_n) begin
            field_storage.CLKDIV.cpol.value <= 1'h0;
        end else begin
            if(field_combo.CLKDIV.cpol.load_next) begin
                field_storage.CLKDIV.cpol.value <= field_combo.CLKDIV.cpol.next;
            end
        end
    end
    assign hwif_out.CLKDIV.cpol.value = field_storage.CLKDIV.cpol.value;
    // Field: axi_qspi_regs.SPICMD.cmd
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SPICMD.cmd.value;
        load_next_c = '0;
        if(decoded_reg_strb.SPICMD && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SPICMD.cmd.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.SPICMD.cmd.next = next_c;
        field_combo.SPICMD.cmd.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.SPICMD.cmd.load_next) begin
            field_storage.SPICMD.cmd.value <= field_combo.SPICMD.cmd.next;
        end
    end
    assign hwif_out.SPICMD.cmd.value = field_storage.SPICMD.cmd.value;
    // Field: axi_qspi_regs.SPIADR.addr
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SPIADR.addr.value;
        load_next_c = '0;
        if(decoded_reg_strb.SPIADR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SPIADR.addr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.SPIADR.addr.next = next_c;
        field_combo.SPIADR.addr.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.SPIADR.addr.load_next) begin
            field_storage.SPIADR.addr.value <= field_combo.SPIADR.addr.next;
        end
    end
    assign hwif_out.SPIADR.addr.value = field_storage.SPIADR.addr.value;
    // Field: axi_qspi_regs.SPILEN.len
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SPILEN.len.value;
        load_next_c = '0;
        if(decoded_reg_strb.SPILEN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SPILEN.len.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.SPILEN.len.next = next_c;
        field_combo.SPILEN.len.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.SPILEN.len.load_next) begin
            field_storage.SPILEN.len.value <= field_combo.SPILEN.len.next;
        end
    end
    assign hwif_out.SPILEN.len.value = field_storage.SPILEN.len.value;
    // Field: axi_qspi_regs.SPIDUM.dum
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SPIDUM.dum.value;
        load_next_c = '0;
        if(decoded_reg_strb.SPIDUM && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SPIDUM.dum.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.SPIDUM.dum.next = next_c;
        field_combo.SPIDUM.dum.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.SPIDUM.dum.load_next) begin
            field_storage.SPIDUM.dum.value <= field_combo.SPIDUM.dum.next;
        end
    end
    assign hwif_out.SPIDUM.dum.value = field_storage.SPIDUM.dum.value;
    // Field: axi_qspi_regs.TXFIFO.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.TXFIFO.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.TXFIFO && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.TXFIFO.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.TXFIFO.data.next = next_c;
        field_combo.TXFIFO.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.TXFIFO.data.load_next) begin
            field_storage.TXFIFO.data.value <= field_combo.TXFIFO.data.next;
        end
    end
    assign hwif_out.TXFIFO.data.value = field_storage.TXFIFO.data.value;
    assign hwif_out.TXFIFO.data.swacc = decoded_reg_strb.TXFIFO;
    assign hwif_out.RXFIFO.data.swacc = decoded_reg_strb.RXFIFO;
    // Field: axi_qspi_regs.CS_DEF.cs
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CS_DEF.cs.value;
        load_next_c = '0;
        if(decoded_reg_strb.CS_DEF && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CS_DEF.cs.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CS_DEF.cs.next = next_c;
        field_combo.CS_DEF.cs.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge hwif_in.rst_n) begin
        if(~hwif_in.rst_n) begin
            field_storage.CS_DEF.cs.value <= 32'h0;
        end else begin
            if(field_combo.CS_DEF.cs.load_next) begin
                field_storage.CS_DEF.cs.value <= field_combo.CS_DEF.cs.next;
            end
        end
    end
    assign hwif_out.CS_DEF.cs.value = field_storage.CS_DEF.cs.value;
    // Field: axi_qspi_regs.CS_A_0.val
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CS_A_0.val.value;
        load_next_c = '0;
        if(decoded_reg_strb.CS_A_0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CS_A_0.val.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CS_A_0.val.next = next_c;
        field_combo.CS_A_0.val.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.CS_A_0.val.load_next) begin
            field_storage.CS_A_0.val.value <= field_combo.CS_A_0.val.next;
        end
    end
    assign hwif_out.CS_A_0.val.value = field_storage.CS_A_0.val.value;
    // Field: axi_qspi_regs.CS_M_0.val
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CS_M_0.val.value;
        load_next_c = '0;
        if(decoded_reg_strb.CS_M_0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CS_M_0.val.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CS_M_0.val.next = next_c;
        field_combo.CS_M_0.val.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.CS_M_0.val.load_next) begin
            field_storage.CS_M_0.val.value <= field_combo.CS_M_0.val.next;
        end
    end
    assign hwif_out.CS_M_0.val.value = field_storage.CS_M_0.val.value;
    // Field: axi_qspi_regs.CS_A_1.val
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CS_A_1.val.value;
        load_next_c = '0;
        if(decoded_reg_strb.CS_A_1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CS_A_1.val.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CS_A_1.val.next = next_c;
        field_combo.CS_A_1.val.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.CS_A_1.val.load_next) begin
            field_storage.CS_A_1.val.value <= field_combo.CS_A_1.val.next;
        end
    end
    assign hwif_out.CS_A_1.val.value = field_storage.CS_A_1.val.value;
    // Field: axi_qspi_regs.CS_M_1.val
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CS_M_1.val.value;
        load_next_c = '0;
        if(decoded_reg_strb.CS_M_1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CS_M_1.val.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CS_M_1.val.next = next_c;
        field_combo.CS_M_1.val.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.CS_M_1.val.load_next) begin
            field_storage.CS_M_1.val.value <= field_combo.CS_M_1.val.next;
        end
    end
    assign hwif_out.CS_M_1.val.value = field_storage.CS_M_1.val.value;
    // Field: axi_qspi_regs.CS_A_2.val
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CS_A_2.val.value;
        load_next_c = '0;
        if(decoded_reg_strb.CS_A_2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CS_A_2.val.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CS_A_2.val.next = next_c;
        field_combo.CS_A_2.val.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.CS_A_2.val.load_next) begin
            field_storage.CS_A_2.val.value <= field_combo.CS_A_2.val.next;
        end
    end
    assign hwif_out.CS_A_2.val.value = field_storage.CS_A_2.val.value;
    // Field: axi_qspi_regs.CS_M_2.val
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CS_M_2.val.value;
        load_next_c = '0;
        if(decoded_reg_strb.CS_M_2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CS_M_2.val.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CS_M_2.val.next = next_c;
        field_combo.CS_M_2.val.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.CS_M_2.val.load_next) begin
            field_storage.CS_M_2.val.value <= field_combo.CS_M_2.val.next;
        end
    end
    assign hwif_out.CS_M_2.val.value = field_storage.CS_M_2.val.value;
    // Field: axi_qspi_regs.CS_A_3.val
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CS_A_3.val.value;
        load_next_c = '0;
        if(decoded_reg_strb.CS_A_3 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CS_A_3.val.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CS_A_3.val.next = next_c;
        field_combo.CS_A_3.val.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.CS_A_3.val.load_next) begin
            field_storage.CS_A_3.val.value <= field_combo.CS_A_3.val.next;
        end
    end
    assign hwif_out.CS_A_3.val.value = field_storage.CS_A_3.val.value;
    // Field: axi_qspi_regs.CS_M_3.val
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CS_M_3.val.value;
        load_next_c = '0;
        if(decoded_reg_strb.CS_M_3 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CS_M_3.val.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CS_M_3.val.next = next_c;
        field_combo.CS_M_3.val.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.CS_M_3.val.load_next) begin
            field_storage.CS_M_3.val.value <= field_combo.CS_M_3.val.next;
        end
    end
    assign hwif_out.CS_M_3.val.value = field_storage.CS_M_3.val.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[16];
    assign readback_array[0][15:0] = '0;
    assign readback_array[0][19:16] = (decoded_reg_strb.STATUS && !decoded_req_is_wr) ? hwif_in.STATUS.rx_cnt.next : '0;
    assign readback_array[0][23:20] = '0;
    assign readback_array[0][27:24] = (decoded_reg_strb.STATUS && !decoded_req_is_wr) ? hwif_in.STATUS.tx_cnt.next : '0;
    assign readback_array[0][31:28] = '0;
    assign readback_array[1][7:0] = (decoded_reg_strb.CLKDIV && !decoded_req_is_wr) ? field_storage.CLKDIV.div.value : '0;
    assign readback_array[1][8:8] = (decoded_reg_strb.CLKDIV && !decoded_req_is_wr) ? field_storage.CLKDIV.bypass.value : '0;
    assign readback_array[1][30:9] = '0;
    assign readback_array[1][31:31] = (decoded_reg_strb.CLKDIV && !decoded_req_is_wr) ? field_storage.CLKDIV.cpol.value : '0;
    assign readback_array[2][31:0] = (decoded_reg_strb.SPICMD && !decoded_req_is_wr) ? field_storage.SPICMD.cmd.value : '0;
    assign readback_array[3][31:0] = (decoded_reg_strb.SPIADR && !decoded_req_is_wr) ? field_storage.SPIADR.addr.value : '0;
    assign readback_array[4][31:0] = (decoded_reg_strb.SPILEN && !decoded_req_is_wr) ? field_storage.SPILEN.len.value : '0;
    assign readback_array[5][31:0] = (decoded_reg_strb.SPIDUM && !decoded_req_is_wr) ? field_storage.SPIDUM.dum.value : '0;
    assign readback_array[6][31:0] = (decoded_reg_strb.RXFIFO && !decoded_req_is_wr) ? hwif_in.RXFIFO.data.next : '0;
    assign readback_array[7][31:0] = (decoded_reg_strb.CS_DEF && !decoded_req_is_wr) ? field_storage.CS_DEF.cs.value : '0;
    assign readback_array[8][31:0] = (decoded_reg_strb.CS_A_0 && !decoded_req_is_wr) ? field_storage.CS_A_0.val.value : '0;
    assign readback_array[9][31:0] = (decoded_reg_strb.CS_M_0 && !decoded_req_is_wr) ? field_storage.CS_M_0.val.value : '0;
    assign readback_array[10][31:0] = (decoded_reg_strb.CS_A_1 && !decoded_req_is_wr) ? field_storage.CS_A_1.val.value : '0;
    assign readback_array[11][31:0] = (decoded_reg_strb.CS_M_1 && !decoded_req_is_wr) ? field_storage.CS_M_1.val.value : '0;
    assign readback_array[12][31:0] = (decoded_reg_strb.CS_A_2 && !decoded_req_is_wr) ? field_storage.CS_A_2.val.value : '0;
    assign readback_array[13][31:0] = (decoded_reg_strb.CS_M_2 && !decoded_req_is_wr) ? field_storage.CS_M_2.val.value : '0;
    assign readback_array[14][31:0] = (decoded_reg_strb.CS_A_3 && !decoded_req_is_wr) ? field_storage.CS_A_3.val.value : '0;
    assign readback_array[15][31:0] = (decoded_reg_strb.CS_M_3 && !decoded_req_is_wr) ? field_storage.CS_M_3.val.value : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<16; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
